# Generated by Django 4.1.4 on 2022-12-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_upvote_post_upvoted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvoted_by',
        ),
    ]
