# Generated by Django 4.1.4 on 2022-12-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='continent',
            field=models.CharField(default='prout', max_length=20),
            preserve_default=False,
        ),
    ]
