# Generated by Django 4.1.4 on 2022-12-23 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0010_post_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-id"]},
        ),
    ]
