# Generated by Django 4.1.4 on 2022-12-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0011_alter_post_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="author",
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name="photo",
            name="image_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
