# Generated by Django 4.1.4 on 2022-12-31 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0012_photo_author_photo_image_url_alter_photo_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("review",)},
        ),
    ]
