# Generated by Django 4.1.4 on 2022-12-19 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_upvotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'post')},
        ),
    ]
