name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - name: Generate Report
      run: |
        pip install coverage
        coverage run manage.py test --pattern="test_*.py"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
