name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.9
    - name: Generate Report
      run: |
        pip install coverage
        pip install pytest
        pip install django
        python3 -m coverage run manage.py test --pattern="test_*.py"
        python3 -m coverage report --rcfile=.coveragerc
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
